title:            Raul Fraile
tagline:          A short tagline2
description:      Describe your website2.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://localhost:4000

# Owner/author information
owner:
  name:           Raúl Fraile
  avatar:         bio-photo.jpg
  bio:            "PHP/Symfony2 developer. abc[x](http://ua.es)"
  email:          raulfraile@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        raulfraile
  facebook:       
  github:         raulfraile
  linkedin:       raulfrailebeneyto/en
  instagram:      raulfraile
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About me
    url: /about/
  - title: Blog
    url: /blog/
  - title: Talks
    url: /talks/
  - title: Projects
    url: /projects/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]